export const SUPABASE_URL = 'https://cuaxulqyrhosqbfaympv.supabase.co'
export const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1YXh1bHF5cmhvc3FiZmF5bXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAwNjA2MzYsImV4cCI6MjEwNTYzNjYzNn0.fzvR8P3WhZxnuGnauxCAn4VZKwjvw0jlSTSuMF95oA'
