import { useState, type FormEvent } from 'react'
import { Building2, LockKeyhole, Mail, ShieldCheck } from 'lucide-react'
import { supabase } from './lib/supabase'

export default function AuthScreen() {
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [mode,setMode]=useState<'login'|'signup'>('login');const [loading,setLoading]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('')
  const redirectTo=window.location.origin+import.meta.env.BASE_URL
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');setMessage('');const result=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{emailRedirectTo:redirectTo}});if(result.error)setError(result.error.message);else if(mode==='signup')setMessage('Registrazione completata. Se la conferma email è attiva, controlla la casella di posta.');setLoading(false)}
  async function microsoft(){setLoading(true);setError('');const {error}=await supabase.auth.signInWithOAuth({provider:'azure',options:{redirectTo,scopes:'email openid profile User.Read'}});if(error)setError(error.message);setLoading(false)}
  async function reset(){if(!email){setError('Inserisci prima l’indirizzo email.');return}setLoading(true);setError('');const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo});if(error)setError(error.message);else setMessage('Se l’account esiste, riceverai le istruzioni per reimpostare la password.');setLoading(false)}
  return <div className="auth-shell"><div className="auth-card"><div className="auth-brand"><div className="brand-mark"><Building2 size={25}/></div><div><strong>Gestione Appalti</strong><span>Edilizia e lavori pubblici</span></div></div><div className="auth-title"><h1>Accesso al sistema</h1><p>Gestisci edifici, interventi, finanziamenti e fascicoli in un unico ambiente.</p></div><form onSubmit={submit} className="form-stack"><label>Email<div className="input-icon"><Mail size={17}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="nome@ente.it"/></div></label><label>Password<div className="input-icon"><LockKeyhole size={17}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} placeholder="••••••••"/></div></label><button className="btn primary full" disabled={loading}>{loading?'Attendere…':mode==='login'?'Accedi':'Crea account'}</button></form><button className="btn microsoft full" onClick={microsoft} disabled={loading}><span className="ms-logo">⊞</span> Accedi con Microsoft</button><button className="link-btn" onClick={reset} disabled={loading}>Password dimenticata?</button><div className="auth-divider"><span>oppure</span></div><button className="btn secondary full" onClick={()=>{setMode(mode==='login'?'signup':'login');setError('');setMessage('')}}>{mode==='login'?'Crea un nuovo account':'Ho già un account'}</button><div className="security-note"><ShieldCheck size={16}/><span>Accesso protetto da Supabase Auth e autorizzazioni RLS sul database.</span></div>{message&&<div className="notice success">{message}</div>}{error&&<div className="notice error">{error}</div>}</div></div>
}
